---
output:
  html_document: 
    theme: cerulean
    toc: true
    toc_float: true
    toc_depth: 4
---




```{r setKnitrOptions, include=FALSE}
knitr::opts_chunk$set(results='asis', echo = FALSE, error = TRUE, cache = FALSE, cache.comments = TRUE, fig.dim = c(7,7), autodep = TRUE)
```




```{r loadParamsAndDependencies, warning=FALSE, message=FALSE}

# create the analysis output dir
dir.create( PATH_ANALYSIS_OUTPUT, showWarnings = FALSE, recursive = FALSE)

### Load general Deps
cat("<BR>WORKING_DIR=", WORKING_DIR)
source( file.path( WORKING_DIR, "00_generalDeps.R"));

# Import chunks from source files
read_chunk( path=file.path( WORKING_DIR, "01_prepareData.R"));
```

---
title: `r paste(SAMPLE_NAME, PROJECT_NAME, LITERAL_TITLE, sep ="<BR>")`
---


```{r initFunctions}

### Create output directory
dir.create( PATH_ANALYSIS_OUTPUT, showWarnings = FALSE);


### Record starting time (for report and file names)
startTime = Sys.time();
startTimeReport   = format( startTime, "%Y %m %d %H:%M:%S")
startTimeFileName = format( startTime, "%Y_%m_%d_%H_%M_%S")


### Initialize utils

# Create a hash for all parameters
paramsHash = digest( paramsEnv, algo="murmur32");

# Create a 'safe' unique prefix for output files
outputFilesPrefix = path_sanitize( gsub("([[:punct:]])|\\s+", 
                                        "_", 
                                        paste0(PROJECT_NAME, "_",
                                               SAMPLE_NAME, "_")),
                                   replacement = "_");

# Set seed for pseudo random number generator
set.seed(42);

# Create a hidden empty heatmap to prevent heatmapr interference with plotly functions (bug ?)
cat('<div style="display: none">');
main_heatmap(matrix(0));
cat('</div>');
```




## Primary analysis (QC)


### Run informations {.tabset .tabset-fade}

#### Run
<center>
```{r runInfo_run}
pander( c( 'Date'     = startTimeReport,
           'Sample'   = SAMPLE_NAME,
           'Hash'     = paramsHash));
```
</center>

#### Parameters
```{r runInfo_params}
#showSimpleDT( paramsEnv); # Does not handle lists or nested lists easily
listParams = as.list( paramsEnv);
pander(listParams[order(names(listParams))]); # Show params in alphabetical order
```

#### System
<center>
```{r runInfo_sysInfo}
showSimpleDT( Sys.info())
```
</center>

#### R
```{r runInfo_r}
pander( sessionInfo());
```

<!-- Ending the tabset section -->
### {.toc-ignore} 
<br /><br />


### Filtering & normalization
```{r dataLoadFilterNormalize}
<<loadData>>
<<filterData>>
<<normalizeData>>
```
<br /><br />

### Save Seurat object to RDS file
```{r saveSeuratObject}
saveRDS( custom.rna.seurat, file = file.path( PATH_ANALYSIS_OUTPUT, "custom.rna.seurat.RDS"))
```
<br /><br />
